### ISSUE TITLE
Preprocess the dataset : Handling NULL values & Duplicate features

### ISSUE THREAD

**Issue by sagnik1511** [gdscjgec/Rhythm-Finder#1]
# Problem Statement: 
---
First, run the [notebook](https://github.com/gdscjgec/Rhythm-Finder/blob/main/Rhythm-Finder%20Data%20Processing%20and%20Model%20Preparation%20Notebook.ipynb) and preprocess the dataset with given steps :

## Steps: 
**1. Relacing Null values:** If null values are present then intelligently handle those.
**2. Remove unwanted features or rows:** If there are features with low variance, constant feature, then omit those. If there are duplicate data in the dataset omit those too.

The update should reflect in the notebook.

**Comment by nilupulmanodya** [comment]
I would like to contribute in this issue

**Comment by sagnik1511** [comment]
Assigned @nilupulmanodya.

**Comment by nilupulmanodya** [comment]
> Assigned @nilupulmanodya.

Need Clarification :
_2. Remove unwanted features or rows: _**If there are features with low variance**_, constant feature, then omit those. If there are duplicate data in the dataset omit those too._

Here dataset have 19 data columns and 4 of them are categorical.('artists', 'id' ,'name' and 'release_date').' id ' is already dropped. Other features also has low variance data, but I think those rows need for future processing. Is it need to omit those low variance data?

**Comment by sagnik1511** [comment]
As the specific numeric features can have some importance when clustering, you can avoid dropping those features. Rather than that if you find any data with almost constant distribution feel free to drop those.

P.S. remember to state the modifications you did in your PR. Happy contributing!
