### ISSUE TITLE
Add Background Image to the web-application

### ISSUE THREAD

**Issue by sagnik1511** [gdscjgec/Rhythm-Finder#4]
## 🚀 Feature

**Add a background image for the web application. The image should be in `.jpg` or `.png` format.**

**Procedure :**
The contributors should take the following steps : 
1. Opt for a relevant image for background (must be in the required format).
2. Name that `bg.jpg`.
3. Push that to the assets folder.
4. Add the image as streamlit-server background. For reference, you can check [this](https://github.com/sagnik1511/Lifely/blob/main/heart_disease_app.py#:~:text=main_bg_ext%20%3D%20%22png%22-,st.markdown(,),-st.sidebar.header).

**Comment by AnuragYadav365** [comment]
Hey @sagnik1511, I can work on this issue! Can you assign this?

**Comment by sagnik1511** [comment]
Yes @AnuragYadav365 , sure! Go Ahead. Assigning you.
P.S. Do not add any environment files when pushing to the main!

**Comment by sagnik1511** [comment]
Hey @AnuragYadav365, Can you share a screenshot of the updated streamlit page?

**Comment by AnuragYadav365** [comment]
okay for sure, wait!

**Comment by AnuragYadav365** [comment]
![snap](https://user-images.githubusercontent.com/88428881/135818874-e17d028e-8cc5-496e-a17d-cf393b34fe2d.JPG)
For reference, the background image is taken from unsplash!

**Comment by sagnik1511** [comment]
Yeah, looks nice. Have you validated that if this image is licensable or not?

**Comment by AnuragYadav365** [comment]
yeah, unsplash provided freely usable images. So, you can use in the web application. 👍

**Comment by sagnik1511** [comment]
Closed #4!

**Comment by sagnik1511** [comment]
Closed #4!
